import { Sparkles, Lightbulb, Compass } from 'lucide-react';
import type { DnaResponse } from '../hooks';

interface LiteraryCodexSectionProps {
  profile?: DnaResponse;
}

export function LiteraryCodexSection({ profile }: LiteraryCodexSectionProps) {
  const narration = profile?.narration;
  const personality = profile?.personality;

  if (!narration && !personality) return null;

  return (
    <section className="lb-profile-section lb-codex-section">
      <div className="lb-profile-section-header">
        <h2 className="lb-profile-section-title">
          <Sparkles size={14} className="lb-gold-icon" />
          LITERARY CODEX & AI READING DNA
        </h2>
        {personality?.primaryLabel && (
          <span className="lb-codex-archetype-pill">
            ✦ {personality.primaryLabel}
          </span>
        )}
      </div>

      <div className="lb-codex-card">
        {/* Quote & AI Persona */}
        {narration?.identity && (
          <div className="lb-codex-quote-box">
            <p className="lb-codex-quote">"{narration.identity}"</p>
            <span className="lb-codex-attribution">— generated by AI Reader Intelligence ✦</span>
          </div>
        )}

        {/* Strengths Tags */}
        {narration?.strengths && narration.strengths.length > 0 && (
          <div className="lb-codex-strengths-row">
            <span className="lb-codex-strengths-label">
              <Lightbulb size={12} /> KEY STRENGTHS
            </span>
            <div className="lb-codex-pills-wrap">
              {narration.strengths.map((s: string, i: number) => (
                <span key={i} className="lb-codex-strength-pill">{s}</span>
              ))}
            </div>
          </div>
        )}

        {/* Exploration Suggestion */}
        {narration?.explorationSuggestion && (
          <div className="lb-codex-suggestion-box">
            <p className="lb-codex-suggestion-text">
              <span className="lb-gold-text">Codex Recommendation: </span>
              {narration.explorationSuggestion}
            </p>
          </div>
        )}

        {/* AI Personality Explanation */}
        {narration?.explanation && (
          <div className="lb-codex-rationale-box">
            <div className="lb-codex-rationale-header">
              <Compass size={13} />
              <span>Personality Synthesis</span>
            </div>
            <p className="lb-codex-rationale-text">{narration.explanation}</p>
          </div>
        )}
      </div>
    </section>
  );
}
