interface DnaNarrationProps {
  identity?: string | null;
  archetypeLabel?: string | null;
  version?: string;
}

export function DnaNarration({ identity, archetypeLabel, version }: DnaNarrationProps) {
  if (!identity && !archetypeLabel) {
    return (
      <div className="dna-narration-box" style={{ borderLeft: '2px solid var(--dna-accent)' }}>
        <p className="dna-narration-text" style={{ fontStyle: 'normal' }}>
          Log 5 books to unlock your reading identity
        </p>
      </div>
    );
  }

  return (
    <div className="dna-narration-box" key={version || 'narration'}>
      <p className="dna-narration-text">
        {identity || `You read with the perspective of a ${archetypeLabel || 'reader'}.`}
      </p>
      {identity && (
        <span className="dna-narration-attribution">— generated by AI ✦</span>
      )}
    </div>
  );
}
